fastlane_version "1.81.0"

default_platform :mac

platform :mac do
  before_all do
    carthage(platform: "Mac", use_ssh: true)
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    ensure_git_status_clean
    gym(scheme: "Bailiff") # Build your app - more options available
    zip(path: "Bailiff.app")
    hockey(ipa: "Bailiff.app.zip", dsym: "Bailiff.app.dSYM.zip")
    reset_git_repo(exclude: "Carthage")
  end

end
